name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Compile PEG grammar
      run: npm run compile

    - name: Build project
      run: npm run build

    - name: List project files
      run: ls -R

    - name: Upload Dist Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        name: 'dist-artifacts'

    - name: Upload Frontend Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: './Frontend/'
        name: 'frontend-artifacts'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
    - name: Download Dist Artifacts
      uses: actions/download-artifact@v3
      with:
        name: 'dist-artifacts'
        path: './deploy/dist'

    - name: Download Frontend Artifacts
      uses: actions/download-artifact@v3
      with:
        name: 'frontend-artifacts'
        path: './deploy/frontend'

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: 'frontend-artifacts'
